channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python
  - pywinauto=0.6.8
  - pynput=1.7.3
  #- pip
  - pyautogui
  - pywin32==225 
  #- pip:
    # Define pip packages here. 
    # https://pypi.org/
    #- rpaframework==15.6.0 # https://rpaframework.org/releasenotes.html
